services:
  postgres:
    image: postgres:16
    container_name: dataflowx-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataflowx_db
    ports:
      - "8080:8080"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: